---
- name: Import Tailscale GPG Key
  ansible.builtin.get_url:
    url: https://pkgs.tailscale.com/stable/ubuntu/{{ ubuntu_codename }}.noarmor.gpg
    dest: /etc/apt/keyrings/tailscale.gpg
    mode: '0644'

- name: Add Tailscale Apt Repository
  ansible.builtin.deb822_repository:
    name: tailscale
    types: [deb]
    uris: https://pkgs.tailscale.com/stable/ubuntu
    suites: ["{{ ubuntu_codename }}"]
    components: [main]
    architectures: [amd64]
    signed_by: /etc/apt/keyrings/tailscale.gpg
    state: present

- name: Install Tailscale Package
  ansible.builtin.apt:
    package: [tailscale]
    update_cache: true
    state: present

- name: Start Tailscale Service
  ansible.builtin.service:
    name: tailscaled
    state: started
    enabled: true

- name: Check Tailscale Status
  ansible.builtin.command:
    cmd: tailscale status --json
  register: tailscale_status
  changed_when: false
  failed_when: false

- name: Authenticate Tailscale
  ansible.builtin.command:
    cmd: tailscale up --auth-key={{ tailscale_auth_key }} --hostname={{ inventory_hostname }}
  register: tailscale_up
  changed_when: true
  when:
    - tailscale_auth_key | length > 0
    - tailscale_status.rc != 0 or (tailscale_status.stdout | from_json).BackendState != 'Running'
